{% set version = "3.3-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatstat.explore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.explore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.explore/spatstat.explore_{{ version }}.tar.gz
  sha256: ccbfe3c33195e8ddbad7a3ad75a9f2a259408d244d9197f165ef8777504f2e26

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-abind                    # [build_platform != target_platform]
    - r-goftest                  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-nlme                     # [build_platform != target_platform]
    - r-spatstat.data            # [build_platform != target_platform]
    - r-spatstat.geom            # [build_platform != target_platform]
    - r-spatstat.random          # [build_platform != target_platform]
    - r-spatstat.sparse          # [build_platform != target_platform]
    - r-spatstat.univar          # [build_platform != target_platform]
    - r-spatstat.utils           # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-abind
    - r-goftest >=1.2_2
    - r-matrix
    - r-nlme
    - r-spatstat.data >=3.0_4
    - r-spatstat.geom >=3.3_0
    - r-spatstat.random >=3.3_0
    - r-spatstat.sparse >=3.1_0
    - r-spatstat.univar >=3.0_0
    - r-spatstat.utils >=3.0_5
  run:
    - r-base
    - r-abind
    - r-goftest >=1.2_2
    - r-matrix
    - r-nlme
    - r-spatstat.data >=3.0_4
    - r-spatstat.geom >=3.3_0
    - r-spatstat.random >=3.3_0
    - r-spatstat.sparse >=3.1_0
    - r-spatstat.univar >=3.0_0
    - r-spatstat.utils >=3.0_5

test:
  commands:
    - $R -e "library('spatstat.explore')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.explore')\""  # [win]

about:
  home: http://spatstat.org/
  dev_url: https://github.com/spatstat/spatstat.explore
  license: GPL-2.0-or-later
  summary: Functionality for exploratory data analysis and nonparametric analysis of spatial data, mainly spatial point patterns, in the 'spatstat' family of packages. (Excludes analysis of spatial data on a linear network, which is covered by the separate package 'spatstat.linnet'.) Methods include quadrat counts, K-functions
    and their simulation envelopes, nearest neighbour distance and empty space statistics, Fry plots, pair correlation function, kernel smoothed intensity, relative risk estimation with cross-validated bandwidth selection, mark correlation functions, segregation indices, mark dependence diagnostics, and kernel estimates
    of covariate effects. Formal hypothesis tests of random pattern (chi-squared, Kolmogorov-Smirnov, Monte Carlo, Diggle-Cressie-Loosmore-Ford, Dao-Genton, two-stage Monte Carlo) and tests for covariate effects (Cox-Berman-Waller-Lawson, Kolmogorov-Smirnov, ANOVA) are also supported.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
